on:
  push:
    branches:
      - main
      
defaults:
  run:
    working-directory: ./examples

name: EmbeddedProfiler

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master # https://github.com/seanmiddleditch/gha-setup-ninja

    - name: Configure
      run: |
        cmake -S . -B build -G"Ninja"
        
    - name: Build
      run: |
        cd build 
        cmake --build .
        
    - name: Profile
      run: |
        cd build
        ls